---
- name: Create temp files
  file:
    path: /tmp/es/
    state: directory

- name: Copy Docker file
  copy:
    src=elasticsearch-Dockerfile
    dest=/tmp/es/Dockerfile

- name: build and push
  ignore_errors: true
  become: true
  args:
    chdir: /tmp/es/
  command: "{{ item }}"
  with_items:
    - docker build -t elasticsearch-elk .
    - docker image tag elasticsearch-elk "{{ docker_registry }}/elasticsearch-elk"
    - docker push "{{ docker_registry }}/elasticsearch-elk"

- name: Remove temp files
  file:
    path: /tmp/es/
    state: absent
